[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{message}} (quadproduction/issues#{{ticket_number}})"
example = "(quadproduction/issues#111): Fixing ident on bla bla bla"
schema = "(quadproduction/issues#000) : <body>"
schema_pattern = ".* \\(quadproduction/issues#\\d+\\)$"

[[tool.commitizen.customize.questions]]
type = "input"
name = "ticket_number"
message = "Ticket number: "

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Commit message: "
