application_dir = "blender"
executable = "blender_2.81"
schema = "avalon-core:application-1.0"
label = "Blender 2.81"
ftrack_label = "Blender"
icon ="blender"
ftrack_icon = '{}/app_icons/blender.png'
