executable = "houdini_18"
schema = "avalon-core:application-1.0"
application_dir = "houdini"
label = "Houdini 18"
ftrack_label = "Houdini"
icon = "houdini_icon"
ftrack_icon = '{}/app_icons/houdini.png'
