executable = "photoshop_2020"
schema = "avalon-core:application-1.0"
application_dir = "photoshop"
label = "Adobe Photoshop 2020"
icon ="photoshop_icon"
ftrack_label = "Photoshop"
ftrack_icon = '{}/app_icons/photoshop.png'
launch_hook = "pype/hooks/photoshop/prelaunch.py/PhotoshopPrelaunch"
