schema = "avalon-core:application-1.0"
application_dir = "python"
executable = "python3"
label = "Python 3"
ftrack_label = "Python"
icon ="python_icon"
ftrack_icon = '{}/app_icons/python.png'

[environment]
CREATE_NEW_CONSOLE = "Yes"
