name: 📦 Build Zip Patch

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'
      - 'CI/*.*.*-*'
  workflow_dispatch:

jobs:
  build-zip-patch:
    runs-on: [self-hosted, ubuntu]

    steps:
    
    - name: 📩 Message to Release chat
      uses: julb/action-post-googlechat-message@v1
      with:
        message: "Hello from Github Action!"
        gchat_webhook_url: ${{ secrets.GCHAT_RELEASE_WEBHOOK_URL }}
        
    - name: 🚛 Checkout Code
      uses: actions/checkout@v3
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 🧵 Install Requirements
      run: ./tools/create_env.sh && ./tools/fetch_thirdparty_libs.sh

    - name: 🔨 Build
      run: tools/create_zip.sh --path /prod/softprod/apps/openpype/REPOSITORY/
