name: 📦 Build Zip Patch

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'
      - 'CI/*.*.*-*'
  workflow_dispatch:

jobs:
  build-zip-patch:
    runs-on: [self-hosted, ubuntu]

    steps:
        
    - name: 🚛 Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: "Build Changelog"
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        fromTag: "3.15.7"
        toTag: "3.15.8"
      env:
        GITHUB_TOKEN: ${{ secrets.QUAD_PUBLIC_GITHUB_TOKEN }}
            
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 🧵 Install Requirements
      run: ./tools/create_env.sh && ./tools/fetch_thirdparty_libs.sh

    - name: 🔨 Build
      run: tools/create_zip.sh --path /prod/softprod/apps/openpype/REPOSITORY/
    
#     - name: 💬 Message to Release chat
#       uses: julb/action-post-googlechat-message@v1
#       with:
#         message: "Bonjour,

# Voici la liste des dernières versions déployé🥳, viendra bientot une version spécial quad 😏

# 3.15.10 pour la prod 🚀

# Vous pouvez consulté la liste des nouveautés depuis la 3.15.9 ici: https://github.com/ynput/OpenPype/releases/tag/3.15.10

# Dès à présent disponible dans la version prod de OpenPype 3.15.

# 3.15.10-nightly.2 pour le staging 🚧

# Voici la liste des issues ajouté:"
#         gchat_webhook_url: ${{ secrets.GCHAT_RELEASE_WEBHOOK_URL }}
