name: 📦 Build Zip Patch

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'
      - 'CI/*.*.*-*'
  workflow_dispatch:

jobs:
  build-zip-patch:
    runs-on: [self-hosted, ubuntu]

    steps:
        
    - name: 🚛 Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: "📝 Build Changelog"
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        fromTag: "3.15.6"
        toTag: "3.15.8"
        commitMode: true
        configurationJson: |
            {
              "template": "TEST",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ],
              label_extractor: [
                {
                  "pattern": "(#[0-9]\{4\})",
                  "target": "$1",
                  "flags": "gu"
                },
              ]
            }
      env:
        GITHUB_TOKEN: ${{ secrets.QUAD_PUBLIC_GITHUB_TOKEN }}

    - name: "print msg"
      run: |
        echo ${{steps.changelog.outputs.changelog}}
        echo ${{steps.changelog.outputs.changes}}
        echo ${{steps.changelog.outputs.commits}}

    - name: 💬 Message to Release chat
      uses: julb/action-post-googlechat-message@v1
      with:
        message: ${{steps.changelog.outputs.changelog}}
        gchat_webhook_url: ${{ secrets.GCHAT_RELEASE_WEBHOOK_URL }}

    # - name: 🐍 Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.9

    # - name: 🧵 Install Requirements
    #   run: ./tools/create_env.sh && ./tools/fetch_thirdparty_libs.sh

    # - name: 🔨 Build
    #   run: tools/create_zip.sh --path /prod/softprod/apps/openpype/REPOSITORY/
    
