name: 📇 Code Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number}}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  files_changed:
    runs-on: ubuntu-latest
    outputs:
        changed_python: ${{ steps.changes.outputs.python }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
      - uses: dorny/paths-filter@master
        id: changes
        with:
          filters: |
            python:
              - ["**/*.py"]

  linting:
    needs: files_changed
    if: ${{ needs.files_changed.outputs.changed_python == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Get changed Python files
        id: py-changes
        run: |
          echo "py_files_list=$(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
            | grep .py$ | xargs)" >> $GITHUB_OUTPUT
      - name: Code Check
        uses: wemake-services/wemake-python-styleguide@master
        with:
          reporter: 'github-pr-review'
          path: ${{ steps.py-changes.outputs.py_files_list }}
        env:
          GITHUB_TOKEN: "${{ secrets.YNPUT_BOT_TOKEN }}"
