name: project-actions

on:
  pull_request_target:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  pr_review_started:
    name: pr_review_started
    runs-on: ubuntu-latest
    # -----------------------------
    # conditions are:
    #   - PR issue comment which is not form Ynbot
    #   - PR review comment which is not Hound (or any other bot)
    #   - PR review submitted which is not from Hound (or any other bot) and is not 'Changes requested'
    # -----------------------------
    if: |
      (github.event_name == 'issue_comment' && github.event.comment.user.id != 82967070) ||
      (github.event_name == 'pull_request_review_comment' && github.event.comment.user.type != 'Bot') ||
      (github.event_name == 'pull_request_review' && github.event.review.state != 'changes_requested' && github.event.review.user.type != 'Bot')
    steps:
      - name: Move PR to 'Review In Progress'
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.YNPUT_BOT_TOKEN }}
          organization: ynput
          project_id: 11
          resource_node_id: ${{ github.event.pull_request.node_id }} || ${{ github.event.issue.node_id }}
          status_value: Review In Progress

  # pr_review_requested:
  #   name: pr_review_requested
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested'
  #   steps:
  #     - name: Move PR to 'Change Requested'
  #       uses: leonsteinhaeuser/project-beta-automations@v2.1.0
  #       with:
  #         gh_token: ${{ secrets.YNPUT_BOT_TOKEN }}
  #         organization: ynput
  #         project_id: 11
  #         resource_node_id: ${{ github.event.pull_request.node_id }}
  #         status_value: Change Requested

  size-label:
    name: pr_size_label
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'assigned') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')

    steps:
      - name: Add size label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.YNPUT_BOT_TOKEN }}"
          IGNORED: ".gitignore\n*.md\n*.json"
        with:
          sizes: >
            {
              "0": "XS",
              "100": "S",
              "500": "M",
              "1000": "L",
              "1500": "XL",
              "2500": "XXL"
            }

  label_prs_branch:
    name: pr_branch_label
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'assigned') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
    - name: Label PRs - Branch name detection
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.YNPUT_BOT_TOKEN }}

  label_prs_globe:
    name: pr_globe_label
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'assigned') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
    - name: Label PRs - Globe detection
      uses: actions/labeler@v4.0.3
      with:
        repo-token: ${{ secrets.YNPUT_BOT_TOKEN }}
        configuration-path: ".github/pr-glob-labeler.yml"
        sync-labels: false
