name: project-actions

on:
  pull_request:
    types: [review_requested, closed]
  pull_request_review:
    types: [submitted]

jobs:
  pr_review_requested:
    name: pr_review_requested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    steps:
      - name: Move PR to 'Change Requested'
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.YNPUT_BOT_TOKEN }}
          user: ${{ secrets.CI_USER }}
          organization: ynput
          project_id: 11
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: Change Requested
