name: 🔄 Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # all days at 00:00
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: develop
          head: develop
          merge_method: rebase